# Parker Dunn
(pgdunn@bu.edu | pdunn91@gmail.com)  
Created on July 1st, 2022


__Assignment for COURSERA: Introduction to Deep Learning (via CU Boulder)__

__Assignment:__ Week 3 - CNN Cancer Detection Kaggle Mini-Project


# Early Exploration of the Images

In [3]:
from skimage import io
import glob
from helperfunctions import *

# Grab random image

train_locs = glob.glob("train/*.tif")
file = train_locs[5]
image = io.imread(file)

train\00001b2b5609af42ab0ab276dd4cd41c3e7745b5.tif
<class 'numpy.ndarray'>


In [7]:
print("Learning about 'train_locs'...","\n")
print(train_locs[0])
print(train_locs[0][6:-4])
print("\n")

print("Learning about image object read in by 'io.imread()'...","\n")
print(type(image))
print(image.shape)

Learning about 'train_locs'... 

train\00001b2b5609af42ab0ab276dd4cd41c3e7745b5.tif
00001b2b5609af42ab0ab276dd4cd41c3e7745b5


Learning about image object read in by 'io.imread()'... 

<class 'numpy.ndarray'>
(96, 96, 3)


* 9,216 pixels per image
* Each image is RGB (depth of 3)
* Total: 27,648 features

In [6]:
print(image[0,0])  # this should be pixel 1?

[255 220 247]


In [8]:
print(image[0,0:4]) # first four pixels

[[255 220 247]
 [130  89  93]
 [187 145 133]
 [255 225 221]]


In [8]:
print(image[0,0:4,0])  # Red only from first four pixels

[255 130 187 255]
