# Parker Dunn
(pgdunn@bu.edu | pdunn91@gmail.com)  
Created on July 1st, 2022


__Assignment for COURSERA: Introduction to Deep Learning (via CU Boulder)__

__Assignment:__ Week 3 - CNN Cancer Detection Kaggle Mini-Project


# Early Exploration of the Images

In [2]:
from skimage import io
import glob

# Grab random image

train_locs = glob.glob("train/*.tif")
file = train_locs[5]
image = io.imread(file)

print(type(image))

<class 'numpy.ndarray'>


In [4]:
print(image.shape)

(96, 96, 3)


* 9,216 pixels per image
* Each image is RGB (depth of 3)
* Total: 27,648 features

In [6]:
print(image[0,0])  # this should be pixel 1?

[255 220 247]


In [8]:
print(image[0,0:4]) # first four pixels

[[255 220 247]
 [130  89  93]
 [187 145 133]
 [255 225 221]]


In [9]:
print(image[0,0:4,0])  # Red only from first four pixels

[255 130 187 255]
